### ISSUE TITLE
can't stop download

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_ftp#28]
retr_callback: pls see my coment.
If u uncomment it- Esc still don't stop download. only stops progress (Cud hangs). hm.

**Comment by pohmelie** [comment]
I can't help here, since it's not about python. You can try raise exception [here](https://github.com/pohmelie/cuda_ftp/commit/993ce081f2e7ceda8a1aee82a704eb3970933ccb#diff-743b1adbf37db12e16e01ef62a6f7d72R229). Also, you don't need `client.quit` call, since context manager will try to close connection in any case.
