### ISSUE TITLE
SFTP for Windows

### ISSUE THREAD

**Issue by MonGMZ** [pohmelie/cuda_ftp#40]
Would it be possible to add support for sftp under windows? I think I could relace notepad++ with cudatext if this worked. 
thanks

**Comment by pohmelie** [comment]
This is definitely possible, but since cuda_ftp uses `paramiko` it should be shipped with cuda_ftp plugin.

**Comment by Alexey-T** [comment]
@pohmelie I cannot make sftp works on my Win10 PC. with CudaText. i copied py files to subfolders of "py". "py" is in Python path (sys.path). any lib imports from py. but sftp dont work

(paramiko + all libs which it uses, 3-5 libs)

**Comment by pohmelie** [comment]
@Alexey-T, paramiko depends on [cryptography](https://pypi.python.org/pypi/cryptography), so you also need to ship proper version with cuda (since `cryptography` have binary part).

**Comment by MonGMZ** [comment]
@pohmelie you mean I could add support for sftp in windows just adding the scripts of paramiko and the binary of cryptography in the requests folder of cudatext? 
Thanks

**Comment by pohmelie** [comment]
I don't know exactly in which directory this should be added, but yes, I think it will work.

**Comment by Alexey-T** [comment]
C:\Cudatext\py - this dir has all plugins. It is in sys.path. Enter in console "import sys; print(sys.path);"

**Comment by Alexey-T** [comment]
@pohmelie Can u try to copy all libs to Cudatext (Win32 portable)?

**Comment by pohmelie** [comment]
I have no win machine, sorry. Maybe I have virtual, I will try to check this today.

**Comment by MonGMZ** [comment]
Thanks, because I didn't succeed.

**Comment by pohmelie** [comment]
I've tried some flex solution, where we working with python from cuda console, and I think this is the direction in which this all should going. So, at first, pip have api, and we can call pip from console or our python program. So we need to ship cuda python with pip and setuptools, in that part I have success. But, next installation of `paramiko` breaks cuda very strange way. It looks like python in cuda is cutted, since it have no some checks of output buffer (`isatty`, this can be solved with `-qqq` flag), but also breaks on source distribution package installation with:
```
File "C:\tools\cudatext\py\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
AttributeError: 'NoneType' object has no attribute 'encoding'
```
When pip and setuptools are present, we can install any package with:
`import pip; pip.commands.InstallCommand().main(["-qqq", "paramiko"]); print("done")`

But, unfortunately, this will not install packages to `py` directory, since it looks like it was added in runtime, and python don't realize it as installation path. But to `..\cudatext\Lib`, but plain copy works fine and setuptools installed with success.

Also, I tried `pip download` command with system python and setting platform and python version, but this requires that all packages support binary distribution on pypi, but, as expected, that is not true and downloading breaks.

The easiest way is to create VM with exactly same version of python, install paramiko and copy all stuff from `site-packages` directory to cuda `py`.

You can play with installation (remove setuptools and install it from cuda console, to see some issues) and try to install `paramiko`, to see what is happening (some popups, freeze, etc.).
[cudatext.zip](https://github.com/pohmelie/cuda_ftp/files/832561/cudatext.zip)

**Comment by Alexey-T** [comment]
Python cutted? i got my dll +zip from
https://www.python.org/downloads/windows/
Download Windows x86-64 embeddable zip file

**Comment by Alexey-T** [comment]
It was 3.5, now exists 3.6, also link
Download Windows x86-64 embeddable zip file
from that page. can you try it. (Zip+ dlls + folder DLLs)

**Comment by pohmelie** [comment]
I mean not python himself, but optioning of "console" maybe, paths settings (maybe installation path can't be modified).

**Comment by Alexey-T** [comment]
It may be so, limited some part

**Comment by pohmelie** [comment]
If cuda will have ability to install packages, that will slightly improve its abilities.

**Comment by Alexey-T** [comment]
packages in zip are here - https://sourceforge.net/projects/cudatext/files/addons/

**Comment by Alexey-T** [comment]
Yoy can install python libs. too. using zip like plugins

**Comment by pohmelie** [comment]
I mean python packages, not cuda. Installing by hand is annoying, no one will do that, paramiko have near 15 dependencies recursively.

**Comment by Alexey-T** [comment]
i see now. Hm, maybe someone can make it..

**Comment by MonGMZ** [comment]
> i see now. Hm, maybe someone can make it..
This means it won't be possible  to use sftp with cuda on windows?

**Comment by Alexey-T** [comment]
Possible to add ANY python libs to Cudatext:
plugin must add all folders to its folder, then use `sys.path.append(dir_of_plugin)`

@pohmelie Any update?

**Comment by pohmelie** [comment]
Update about what? Until there will be all binary wheels on pypi for all `paramiko` dependencies, there will be no possibility to install it with `pip`. Of course this can be done by hand as I said above.

**Comment by Alexey-T** [comment]
Update about try to install paramiko and all deps, by hands. I tried it months ago. No sftp result, can't connect

**Comment by pohmelie** [comment]
I didn't say, that I will try this way. It's wrong and annoying.

**Comment by Alexey-T** [comment]
This way "by hands" wont try, but how can we try? for Cudatext only this.

**Comment by Alexey-T** [comment]
I tried this- installed via pip all paramiko deps, then in filemanager i copied all dirs from "site-packages" to Cydatext "py"

**Comment by pohmelie** [comment]
@Alexey-T 
Did you have exactly same version and architecture of python that cudatext use? Did you check, that `paramiko` works on regular python after you install all libs?

**Comment by Alexey-T** [comment]
- yes, same version and bitness
- didnot check in Python itself

**Comment by pohmelie** [comment]
> didnot check in Python itself
This should be done, since you can miss some dependency.

**Comment by Alexey-T** [comment]
I used pip, it installed N folders for paramiko, can miss some?

**Comment by Alexey-T** [comment]
@pohmelie Can you please try it again?

**Comment by pohmelie** [comment]
@Alexey-T 
Actually, I did not try make it "by hand". I will try it today later.

**Comment by Alexey-T** [comment]
I look forward for this.

**Comment by MonGMZ** [comment]
Any advances? sorry for the insistence...

**Comment by Alexey-T** [comment]
Im interested too.

**Comment by pohmelie** [comment]
Still have no time for this.

**Comment by Alexey-T** [comment]
This guy supports Paramiko in portable ST3 plugin
https://github.com/deNULL/RemoteTree

**Comment by Alexey-T** [comment]
@MonGMZ Above it github of ST3 plugin.
I cannot test.
 try this:

- copy all subdirs from this ST plugin, into CudaText's py folder
- copy *.pyd file also there ... if don't work, copy to Cudatext's DLLs folder

**Comment by Alexey-T** [comment]
(Updated post with link to PyPi.org)

**Comment by MonGMZ** [comment]
I tried without any success :(

**Comment by Alexey-T** [comment]
Solved
for Win-64-bit. 
install addon "SFTP support" and update "FTP". Pls test.

**Comment by MonGMZ** [comment]
It works great now, many thanks to all 👍

**Comment by Alexey-T** [comment]
@pohmelie Agree, it is good?

**Comment by pohmelie** [comment]
If it works, then it is good enough.
