### ISSUE TITLE
Allow publickey authentication method for SFTP servers

### ISSUE THREAD

**Issue by RogueScholar** [pohmelie/cuda_ftp#47]
Any chance of getting this functionality added? Obviously the capability exists within the paramiko library, and for the UI part I could see it being as simple as adding a boolean option for publickey auth that would then parse the contents of the password field as a path to the keyfile. If a method were created to also store the keyfile passphrase if desired, then we'd really be cooking with gas! :fire: :wink:

**Comment by Alexey-T** [comment]
@dinkumoil Maybe you know about public keys? I even don’t know what it is and don’t have such server

**Comment by dinkumoil** [comment]
Authentication with a public key is an application of [asymmetric cryptography](https://en.wikipedia.org/wiki/Public-key_cryptography).

A user can create a pair of private and public keys. In case of SFTP the public key has to be stored on the server, the private key is kept secret and is only known by the user.

When the user wants to connect with his SFTP client to the server, the server sends its certificate to the client. If it is the first attempt of the client to connect to this server, the user is prompted to accept and store the received certificate.

If the user chooses to store the certificate, the next time he connects to the same server the SFTP client compares the freshly received certificate with the stored one. If they do not match, the user will be warned and is adviced to abort the connection attempt. If the certificates match, the connection attempt is being continued.

**Please note:** I'm not sure about the following! The SFTP client now encrypts the certificate of the server using the private key, thus the SFTP client needs to know the path to the private key file. After encryption, the certificate is sent back to the server. The server tries to decrypt the received data using the public key file stored at the server. If that succeeds the user is authenticated.

> I even don’t know what it is and don’t have such server

You have such a server. You can set up SFTP access using private key auth to your repositories on _SourceForge_. To create a private/public key pair use _PuTTYgen_.

**Comment by Alexey-T** [comment]
Closing this until someone makes a patch.

**Comment by halfbrained** [comment]
Using key authentication seems to work.  
Now I'm not sure how to ask for a key file, is this alright?
![ftp_change](https://user-images.githubusercontent.com/74829192/109420845-2c209c00-79dd-11eb-9248-58d99dbde1a5.png)

**Comment by Alexey-T** [comment]
@RogueScholar @pohmelie I didn't use 'private keys' yet so what is your point?

**Comment by Alexey-T** [comment]
I opened props of FTP site in DoubleCommands -it shows field for 'private key file', even 2 fields! ot looks like this, when I check "SSH" checkbox

1st tab

![Screenshot from 2021-02-28 18-14-04](https://user-images.githubusercontent.com/4154978/109423551-eb328280-79f0-11eb-9d16-68d940777056.png)

2nd tab for 'SSH" checked

![Screenshot from 2021-02-28 18-14-15](https://user-images.githubusercontent.com/4154978/109423559-f5ed1780-79f0-11eb-9d91-294e8363a6ec.png)

**Comment by halfbrained** [comment]
You can get public key from private, so just private is enough.

**Comment by pohmelie** [comment]
> I didn't use 'private keys' yet so what is your point? maybe some apps do it in other way.

Private/public keys/tokens are everywhere right now. I'm not sure about paramiko, but I think it should support this feature. BTW, how are you pushing to github without private/public ssh pair? :laughing:

**Comment by Alexey-T** [comment]
I use the password. @pohmelie , what do you think about 
https://github.com/pohmelie/cuda_ftp/issues/47#issuecomment-787456058

**Comment by pohmelie** [comment]
> I use the password. @pohmelie , what do you think about
> [#47 (comment)](https://github.com/pohmelie/cuda_ftp/issues/47#issuecomment-787456058)
> what UI to give in dialog for privat keys?

Sounds right, except of design problems with size of inputs.

**Comment by Alexey-T** [comment]
@halfbrained it should look like
```
caption   [...................] [button]
caption   [...................] [button]

private key [..................] [Browse...]
```

**Comment by dinkumoil** [comment]
@Alexey-T 

You should re-read my [comment above from some months ago](#issuecomment-558604351) about private/public key stuff.


@Alexey-T , @halfbrained , @pohmelie 

I'm not sure if it is neccessary to have an input field for both private **and public** key files. Notepad++ _NppFTP_ plugin and _WinSCP_ have only an input field for private key files. The public key has to be installed at the SFTP server before a user can connect, thus it is useless to have this input field.

The only reason I can imagine why _DoubleCommander_ has both of these input fields is, that this program might support installing a public key file on an OpenSSH based SFTP server like _WinSCP_ does. But this seems to be a special use case only valid for OpenSSH based servers.

Have a look at the _WinSCP_ docs about [installing a public key into OpenSSH server](https://winscp.net/eng/docs/ui_login_authentication?ver=5.17.10&lang=0407&utm_source=winscp&utm_medium=app&utm_campaign=5.17.10#private_key)

**Comment by Alexey-T** [comment]
2021.03.06
+ add: SFTP public key authentication support (work by @halfbrained)

@RogueScholar @dinkumoil 
I am asking to test this, if possible, I don't even have the servers to test. TIA.

**Comment by dinkumoil** [comment]
@Alexey-T 

Before testing I updated _CudaText_ to version 1.128.1.0 and FTP plugin to version of 2021-03-06.

1. After starting the FTP plugin, the console windows displays some errors concerning a deleted API:

![grafik](https://user-images.githubusercontent.com/24699812/110249276-bb95f400-7f75-11eb-8a67-dfe2b6c628f8.png)

2. The layout of the plugin's _New server_ / _Edit server_ dialog is buggy:

![grafik](https://user-images.githubusercontent.com/24699812/110249221-78d41c00-7f75-11eb-8445-575b0ac8e958.png)

3. Connecting to my _SourceForge_ repos of my Notepad++ plugins worked, also downloading files into _CudaText_ &#128077;.

4. In the UI of the _New server_ / _Edit server_ dialog it should be explicitely mentioned that the private key file has to be in _Open SSH_ format. This is because Windows users mostly generate private/public key pairs using _PuTTYgen_, which produces keys in a proprietary format that have to be converted into _Open SSH_ format (that can be done by _PuTTYgen_ itself).

**Comment by dinkumoil** [comment]
@Alexey-T 

I forgot to mention, that it is possible to protect private key files with a password. This is common on mobile machines to be able to store the private key file on these machines in encrypted form. Thus, FTP plugin should provide the ability to decrypt password protected private key files. Of course, the UI of the _New server_ / _Edit server_ dialog has to be extended accordingly then.

**Comment by dinkumoil** [comment]
@Alexey-T 

There is the following limitation that is not special to SFTP server entries. Instead, it is a common limitation of the FTP plugin.

It is not possible to create multiple server entries with the same URL. This is annoying if you have for example multiple _SourceForge_ repositories which all have the same URL but different base directories (**Note:** This can not be changed, all _SourceForge_ repos under the same user account have the same URL, they only differ in the base directories).

If you already created a server entry for a _SourceForge_ repo and you try to add another one, the `Initial remote dir` input field of all server entries with the same URL is overwritten with the content of this input field from the newly created server.

**Comment by Alexey-T** [comment]
@dinkumoil I posted your 3 comments links to new issues. Thanks for help.

**Comment by halfbrained** [comment]
@dinkumoil Thank you for the feedback

> I forgot to mention, that it is possible to protect private key files with a password.

Keys encrypted with a passphrase are supported and are functioning for me. What kind of problems did you have?
It should ask for a passphrase on first use of the specific key.

> It is not possible to create multiple server entries with the same URL

I will add unique aliases for servers, that will default to the current form. This seems like an important feature on its own, and has a bonus of fixing this problem :)

**Comment by dinkumoil** [comment]
@halfbrained 

> Keys encrypted with a passphrase are supported and are functioning for me. What kind of problems did you have?
It should ask for a passphrase on first use of the specific key.

Since I have no passphrase protected private key files I did not test this feature. I have not seen an input field for private key passphrase so I thought it might be worth to mention it. If you ask for a passphrase when the private key is used the first time it should be OK - provided you do not write the passphrase into some config file, **this should definitely be avoided!**. But you should remember the passphrase in RAM during current _CudaText_ session to avoid that users have to input it everytime they want to access files on the server.

> I will add unique aliases for servers, that will default to the current form.

Why not introducing a default server name when clicking on `New server`, for example `Server X` where `X` is a automatically generated number? To generate it, the code should look for already existing `Server X` entries and take the first unused number. This way it is not possible for users to accidentally set an already existing alias for a new server entry.

**Comment by halfbrained** [comment]
> you do not write the passphrase into some config file, **this should definitely be avoided!**. But you should remember the passphrase in RAM during current _CudaText_ session to avoid that users have to input it everytime they want to access files on the server.

Yep, that is the way it is implemented

**Comment by dinkumoil** [comment]
@Alexey-T 

I can not provide an _OpenSSH_ private key file in config dialog only because it has _ppk_ as file name extension. This restriction is designed too simple.

If it is not possible/too complicated to check the provided file to be a valid _OpenSSH_ private key file, no check at all should be done. Thus, the plugin will fail when trying to connect to the SFTP server, which should be indicated by a reasonable error message.

**Comment by halfbrained** [comment]
PuTTYgen key format spec was a bit hidden and paramiko doesn't provide a reason for key decryption failure... but now I found the [official description](https://tartarus.org/~simon/putty-snapshots/htmldoc/AppendixC.html#ppk-outer), so I will be checking the file contents.

**Comment by Alexey-T** [comment]
@halfbrained I guess @dinkumoil wants the 'choose file' dialog to allow all filenames, even w/o some extension

**Comment by dinkumoil** [comment]
@halfbrained 

> why do you have an OpenSSH key with a .ppk extension? :)

Because I can.  ;-)

**Comment by halfbrained** [comment]
> @halfbrained I guess @dinkumoil wants the 'choose file' dialog to allow all filenames, even w/o some extension

yeah, I just want to give user a warning if he tries to use wrong key format.

**Comment by dinkumoil** [comment]
>  when @Alexey-T publishes it

Already happened.


@halfbrained ,  @Alexey-T 

Thank you guys!

**Comment by Alexey-T** [comment]
Closing, over-heated topic.
